spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 939873353249541
            client-secret: b50a334993f409cf74cba2217319bf48
            scope:
              - email
              - public_profile
          google:
            client-id: 1032831719499-ih5rcoekq15v41gsf4fpn7f1ms5u58uq.apps.googleusercontent.com
            client-secret: jEr23_2JFq59swJ9DTjIza6f
            scope:
              - email
              - profile